services:
  db:
    image: postgres:16-alpine
    container_name: discount_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4
    container_name: discount_pgadmin
    restart: always
    environment:
      # These are the credentials you'll use to LOG IN to pgAdmin in your browser
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

  streamlit:
    image: discount-tracker-streamlit:1.0
    build: 
      context: .
      target: streamlit
    container_name: discount_streamlit
    restart: unless-stopped # Ensures app restarts in case of crash, but not if stopped manually
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
      - UV_LINK_MODE=${UV_LINK_MODE}
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - /app/.venv
    command: uv run streamlit run discount_tracker_streamlit/app.py --server.port 8501 --server.address 0.0.0.0

  orchestrator:
    image: discount-tracker-orchestrator:1.0
    build: 
      context: .
      target: orchestrator
    container_name: discount_orchestrator
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
      - DBT_PROFILES_DIR=${DBT_PROFILES_DIR}
      - DBT_PROJECT_DIR=${DBT_PROJECT_DIR}
      - UV_LINK_MODE=${UV_LINK_MODE}
    volumes:  
      - .:/app
      - /app/.venv                                                 # Avoid volume conflicts with the virtual environment
      - dbt_packages_volume:/app/discount_tracker_dbt/dbt_packages # Separate volume for dbt_packages to avoid conflicts
    command: sleep infinity

volumes:
  postgres_data:
  dbt_packages_volume: