[project]
name = "discount-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datetime>=6.0",
    "dotenv>=0.9.9",
    "psycopg2-binary>=2.9.11",
    "regex>=2026.1.15"
]

[dependency-groups]
orchestrator = [
    "dbt>=1.0.0.40.14",
    "dbt-core>=1.11.6",
    "dbt-postgres>=1.10.0",
    "scrapy>=2.14.1"
]
streamlit = [
    "streamlit>=1.55.0"
]
