[project]
name = "discount-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datetime>=6.0",
]

[dependency-groups]
scrapy = [
    "google-cloud-storage>=3.1.1",
    "scrapy>=2.14.1",
]

dbt = [
    "dbt-bigquery>=1.11.1"
]

scripts = [
    "google-cloud-workflows>=1.16.0",
]
dev = [
    "pytest>=9.1.1",
    "pyyaml>=6.0.3",
    "sqlfluff>=4.3.0",
    "sqlfluff-templater-dbt>=4.3.0",
]
