name: 'discount_tracker_dbt'
version: '1.0.0'
config-version: 2

# This name is the link to your profiles.yml
profile: 'discount-tracker-bq' 

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

models:
    discount_tracker_dbt:
        staging:
            +materialized: view
            +dataset: dbt_staged
        intermediate:
            +materialized: view
            +dataset: dbt_staged
        analytics:
            +materialized: table
            +dataset: dbt_analytics