name: 'discount_tracker_dbt'
version: '1.0.0'
config-version: 2

# This name is the link to your profiles.yml
profile: 'discount_tracker' 

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]