discount-tracker-bq:
  target: local-dev
  outputs:
    cloud-run-prod:
      type: bigquery
      method: oauth
      # Use the absolute path to the same key you used for Terraform/Scrapy
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: prod # This is where dbt will CREATE your new tables
      threads: 4
      timeout_seconds: 300
      location: "{{ env_var('GCP_REGION') }}" # Must match your GCS bucket/BigQuery dataset location
      priority: interactive
    local-dev:
      type: bigquery
      method: oauth
      # Use the absolute path to the same key you used for Terraform/Scrapy
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: dev # This is where dbt will CREATE your new tables
      threads: 4
      timeout_seconds: 300
      location: "{{ env_var('GCP_REGION') }}" # Must match your GCS bucket/BigQuery dataset location
      priority: interactive
    ci:
      type: bigquery
      method: service-account-json
      keyfile_json: "{{ env_var('GCP_DBT_SA_KEY') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: dev
      threads: 4
      timeout_seconds: 300
      location: "{{ env_var('GCP_REGION') }}"