name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      scrapy_test: ${{ steps.filter.outputs.scrapy_test }}
      scrapy_deploy: ${{ steps.filter.outputs.scrapy_deploy }}
    steps:
    # Set path filters for each case: scrapy test and scrapy deploy
    # Run test on all changes affecting both scrapy and tests
    # Run deploy only if actual code changed (+ docker and uv changes)
    - uses: dorny/paths-filter@v4
      id: filter
      with:
        filters: |
          scrapy_test:
            - 'discount_tracker_scrapy/**'
            - 'pyproject.toml'
            - 'uv.lock'
            - 'Dockerfile'
            - 'tests/spiders/**'
            - 'schemas/spider_required_keys.yaml'
          scrapy_deploy:
            - 'discount_tracker_scrapy/**'
            - 'pyproject.toml'
            - 'uv.lock'
            - 'Dockerfile'
          
  test:
    needs: changes
    if: ${{ needs.changes.outputs.scrapy_test == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write # Required for uv cache
    steps:
      - uses: actions/checkout@v4
        
        # Install uv with cache enabled for faster repeated runs
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
            enable-cache: true

      - name: Install deps
        run: uv sync --dev --group scrapy

      # Runs test on each spider with limited item count
      - name: Test spiders
        run: uv run pytest tests/spiders/ -v

  deploy:
      needs: [changes, test]
      if: |
        github.ref == 'refs/heads/main' && github.event_name == 'push' &&
        ${{ needs.changes.outputs.scrapy_deploy == 'true' }}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push image
          # Double tag to update latest and keep traceability
          run: |
            docker build \
              --target scrapy \
              -t vsantos77/discount-tracker-scrapy:latest \
              -t vsantos77/discount-tracker-scrapy:${{ github.sha }} \
              .
            docker push vsantos77/discount-tracker-scrapy:latest
            docker push vsantos77/discount-tracker-scrapy:${{ github.sha }}

        - name: Auth on GCP
          uses: google-github-actions/auth@v2
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}

        - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@v2

        - name: Update scrapy job image reference
          # Update scrapy cloud run job to point to the recently pushed Docker image
          run: |
            gcloud run jobs update discount-tracker-scrapy-job \
              --image docker.io/vsantos77/discount-tracker-scrapy:${{ github.sha }} \
              --region ${{ vars.GCP_REGION }} \
              --project ${{ vars.GCP_PROJECT_ID }}